apiVersion: v1
kind: ServiceAccount
metadata:
  name: krr-web
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krr-web
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - "apps"
    resources:
      - pods
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
  - verbs:
      - get
      - list
    apiGroups:
      - "batch"
    resources:
      - jobs
      - cronjobs
  - verbs:
      - get
      - list
    apiGroups:
      - "autoscaling"
    resources:
      - horizontalpodautoscalers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krr-web
subjects:
  - kind: ServiceAccount
    name: krr-web
    namespace: default
roleRef:
  kind: ClusterRole
  name: krr-web
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "krr-web"
  labels:
    app.kubernetes.io/name: "krr-web"
    app.kubernetes.io/instance: "krr-web"
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: krr-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: krr-web
      app.kubernetes.io/instance: "krr-web"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: krr-web
        app.kubernetes.io/instance: "krr-web"
    spec:
      containers:
        - name: krr-web
          image: "ijmacd/krr-web:1.1.0"
          command: ["python", "server.py"]
          args:
            - "simple"
            - "-p"
            - "http://prometheus-kube-prometheus-prometheus.prometheus:9090"
            - "--mem-min"
            - "10"
            - "--cpu-min"
            - "5"
            - "--memory-buffer-percentage"
            - "25"
            - "--use-oomkill-data"
            - "--oom-memory-buffer-percentage"
            - "50"
          ports:
            - name: web
              containerPort: 8080
          resources:
            requests:
              cpu: 5m
              memory: 364Mi
            limits:
              memory: 364Mi
      serviceAccountName: krr-web
---
apiVersion: v1
kind: Service
metadata:
  name: "krr-web"
  labels:
    app.kubernetes.io/component: krr-web
    app.kubernetes.io/name: "krr-web"
    app.kubernetes.io/instance: "krr-web"
spec:
  selector:
    app.kubernetes.io/component: krr-web
    app.kubernetes.io/instance: "krr-web"
  # type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 8080
      targetPort: web
